CREATE DATABASE CL1;

USE CL1;

CREATE TABLE products (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,
  price INT NOT NULL,
  
  PRIMARY KEY (id)
);
select * from products